name: PlexRipper add-on
version: "0.1.17"
slug: plexripper
description: PlexRipper add-on
url: "https://github.com/frosit/addon-plexripper"
webui: http://[HOST]:[PORT:7000]
host_network: true
ports:
  7000/tcp: 7000
#ingress_port: 7000
#ingress_stream: false
ingress: false
panel_icon: mdi:cloud-download
startup: services
arch:
  - aarch64
  - amd64
init: false
hassio_api: false
homeassistant_api: false
hassio_role: homeassistant
map:
  - share:rw
  - media:rw
  - addons:rw
  - addon_config:rw
options:
  message: "Hello world..."
  plexripper_root: "/data/PlexRipper"
  plexripper_publish: "/data/publish"
schema:
  message: "str?"
  plexripper_root: "str?"
  plexripper_publish: "str?"
image: "ghcr.io/frosit/{arch}-addon-plexripper"
