name: PlexRipper add-on
version: "0.1.22"
slug: plexripper
description: PlexRipper add-on
url: "https://github.com/frosit/addon-plexripper"
webui: http://[HOST]:[PORT:7000]
host_network: true
ports:
  7000/tcp: 7000
#ingress_port: 7000
#ingress_stream: false
panel_icon: mdi:cloud-download
startup: services
arch:
  - armv7
  - aarch64
  - amd64
  - armhf
  - i386
init: false
hassio_role: homeassistant
map:
  - share:rw
  - media:rw
options:
  plexripper_root: "/data/PlexRipper"
  plexripper_publish: "/data/publish"
schema:
  plexripper_root: "str?"
  plexripper_publish: "str?"
image: "ghcr.io/frosit/{arch}-addon-plexripper"
